### ISSUE TITLE
puppet-agent fails on Solaris 11 with the SRU update #57

### ISSUE THREAD

**Issue by cthorn42** [puppetlabs/puppet-agent#2423]
A new software repository update, SRU, for Solaris 11 has broken the puppet-agent. 
We've gotten a report confirming this for the 7.x branch, waiting for confirmation for 8.x/main branch.
The error is around libffi which comes packaged with Solaris, we currently rely on the 7.x stream of puppet-agent the Solaris system library of libffi. 
On Solaris 11 with a SRU 57 or newer the failure will look something like this:
```
puppet agent --version
Error: Could not initialize global default settings: ld.so.1: ruby: libffi.so.5: open failed: No such file or directory - /opt/puppetlabs/puppet/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi_c.so
```

We need to fix this in the puppet-runtime, this will require a new puppet-agent release in order to fix.

**Comment by joshcooper** [comment]
This is https://perforce.atlassian.net/issues/PA-5929

**Comment by joshcooper** [comment]
This was fixed in https://github.com/puppetlabs/puppet-runtime/pull/776 and https://github.com/puppetlabs/puppet-runtime/pull/777
