### ISSUE TITLE
Is there an alternative to building from github source to create a puppet-agent rpm?

### ISSUE THREAD

**Issue by maureen-lawless** [puppetlabs/puppet-agent#2476]
## Use Case
Are there source rpms available on https://yum.puppetlabs.com/ for the puppet-agent package from which the .spec file could be generated and combined with a puppet-agent tarball from https://downloads.puppetabs.com/ to more easily generate an rpm?

## Describe the Solution You Would Like
I would like to produce/re-package my own puppet-agent rpm. 
With much older (pre all in one package) builds I could use the method described above to generate my own rpm and avoid having to build the rpm from the source on github.

## Describe Alternatives You've Considered
Trying to build the puppet-agent from source as described on github.
Currently i'm unable to build the puppet-runtime project from source, which is a pre-requisite to building the puppet-agent. 
Ticket raised on that:  https://github.com/puppetlabs/puppet-runtime/issues/784

**Comment by joshcooper** [comment]
Hi @maureen-lawless, sorry but we don't have any plans on building or making available source RPMs
