### ISSUE TITLE
user facts based on Time class fails with Tried to load unspecified class: Time

### ISSUE THREAD

**Issue by level-a** [puppetlabs/puppet-agent#2523]
## Describe the Bug
fact fails with error 
```
Error: Facter: Unable to add resolve nil for fact 'factname': Tried to load unspecified class: Time
```

## Steps to Reproduce
create user fact with any Time class methods

## Environment
 - Version 8.6.0
 - Platform Ubuntu 22.04

**Comment by cthorn42** [comment]
@level-a Could we get a more fleshed out reproduction for this? Also is this Ubuntu 22.04 x86_64, arm64, or something else?

**Comment by tvpartytonight** [comment]
Closing out this issue with no response from the submitter; please feel free to re-open if a reproduction case is made.
