### ISSUE TITLE
Please provide puppet-agent package for Ubuntu 24.04

### ISSUE THREAD

**Issue by absld** [puppetlabs/puppet-agent#2546]
## Use Case
We'd like to rollout Ubuntu 24.04 systems, but there are still no puppet-agent .deb packages for noble available within [Puppetlabs' apt repository](https://apt.puppetlabs.com/).

## Describe the Solution You Would Like
Please provide .deb Packages for Ubuntu 24.04 noble. Could you estimate, when puppet-agent packages for Ubuntu 24.04 will be available?

**Comment by joshcooper** [comment]
This is being discussed in https://github.com/puppetlabs/puppet/issues/9332#issuecomment-2168211968 so closing this as a dup.
