### ISSUE TITLE
Publicize PL tools

### ISSUE THREAD

**Issue by roidelapluie** [puppetlabs/puppet-agent#481]
https://github.com/puppetlabs/puppet-agent/blob/master/configs/platforms/el-7-x86_64.rb
contains
http://pl-build-tools.delivery.puppetlabs.net/yum/el/6/
which is not reachable outside Puppetlabs. Plus it is a el6 repo (which is not that important).

**Comment by melissa** [comment]
Hi @roidelapluie Unfortunately, we're not good at keeping up with github issues. Will you open this as a ticket in the CPR project (https://tickets.puppetlabs.com/browse/CPR/)? That way we can get more visibility on this request.

Thanks!
